### ISSUE TITLE
pull and validate with upstream changes in opensha/opensha-ucerf3

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/opensha-ucerf3#4]
We want latest changes from upstream, and these are expected to break a few tests in nshm-nz-opensha. 

- [x] create a tag here for downstream builds to pin to (?? check this is right)
- [x] refactor any local tests if needed
- [x] merge to master

**Comment by voj** [comment]
haven't created a tag yet

**Comment by chrisbc** [comment]
> haven't created a tag yet

I'd already done that, but I forgot to update the issue :(

https://github.com/GNS-Science/opensha-ucerf3/releases/tag/v1.5.2-alpha

& I'd updated travis.yml on our downstream project so it used this tag rather than HEAD.

**Comment by voj** [comment]
@chrisbc should we tag the latest commit with v1.5.2.-alpha2, or should we remove the tag from travis.yml?

**Comment by chrisbc** [comment]
> @chrisbc should we tag the latest commit with v1.5.2.-alpha2, or should we remove the tag from travis.yml?

@voj Assuming we're back to all tests passing at HEAD, then I suppose we can remove the tag in Travis.
